'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DataCollection

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtPatientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatientID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMale As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbFemale As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''asa1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asa1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''asa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asa2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''asa3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents asa3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDuration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscipline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscipline As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lapYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lapYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lapNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lapNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''apfelDocYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apfelDocYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''apfelDocNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apfelDocNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtApfel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApfel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFemale As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNonSmoker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNonSmoker As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHistory As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOpioid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpioid As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''vol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vol As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tiva As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''n2oYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents n2oYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''n2oNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents n2oNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''opioidYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opioidYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''opioidNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opioidNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtOpioidDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpioidDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkPara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPara As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNSAID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNSAID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRegional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRegional As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkKetamine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkKetamine As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMagnesium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMagnesium As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDexmed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDexmed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtRegionalDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegionalDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFluidAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFluidAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hydrationYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydrationYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''hydrationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydrationNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''antiemeticYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents antiemeticYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''antiemeticNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents antiemeticNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''chkDexa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDexa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDexaDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDexaDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkDexaInduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDexaInduction As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDexaIntraop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDexaIntraop As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDexaEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDexaEnd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOndan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOndan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOndanDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOndanDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkOndanInduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOndanInduction As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOndanIntraop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOndanIntraop As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOndanEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOndanEnd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMetro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMetro As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtMetroDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMetroDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkMetroInduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMetroInduction As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMetroIntraop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMetroIntraop As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMetroEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMetroEnd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOthers As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOthersDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOthersDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkOthersInduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOthersInduction As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOthersIntraop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOthersIntraop As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOthersEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOthersEnd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOthersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOthersName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''nauseaT1Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nauseaT1Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''nauseaT1No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nauseaT1No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''nauseaT2Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nauseaT2Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''nauseaT2No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nauseaT2No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''vomitT1Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vomitT1Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''vomitT1No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vomitT1No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''vomitT2Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vomitT2Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''vomitT2No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vomitT2No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''bothT1Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bothT1Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''bothT1No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bothT1No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''bothT2Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bothT2Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''bothT2No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bothT2No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtEpisodesT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEpisodesT1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEpisodesT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEpisodesT2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rescueT1No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rescueT1No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rescueT1Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rescueT1Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rescueT2No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rescueT2No As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rescueT2Yes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rescueT2Yes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtRescueDrugT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRescueDrugT1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRescueDrugT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRescueDrugT2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
